# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  application: YoFi.AspNet
  tests: YoFi.Tests
  functests: YoFi.Tests.Functional

steps:
- checkout: self
  submodules: true

- task: CmdLine@2
  displayName: 'Create version.txt'
  inputs:
    script: 'git describe --long --always --abbrev=8 > $(application)/version.txt'

- task: CmdLine@2
  displayName: 'Create release.txt'
  inputs:
    script: 'git describe --tags > $(application)/release.txt'

- task: DotNetCoreCLI@2
  displayName: 'Publish web app'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--output $(System.DefaultWorkingDirectory)/publish_output --configuration Release'
    zipAfterPublish: false
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: 'Build Functional Tests'
  inputs:
    command: 'build'
    projects: '$(functests)/$(functests).csproj'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    projects: '$(tests)/$(tests).csproj'
    arguments: '--collect:"XPlat Code Coverage" --settings:$(tests)/coverlet.runsettings'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/*/coverage.cobertura.xml'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  artifact: drop